name:  CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  LOCKFILE: lockfile

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: microsoft
        java-version: 17
    - name: Gradle build
      run: ./gradlew :build

  lockfile:
    name: lockfile
    runs-on: ubuntu-latest
    outputs:
      lockfile: ${{ steps.check-lockfile.outputs.create }}
    steps:
    - uses: actions/checkout@v4
    - id: check-lockfile
      run: |
        LOCKFILE=$(find . -type f -name "*.lockfile")
        if [[ ! -z $LOCKFILE ]]; then
            echo "lockfile found. will skip creating."
            echo "create=false" >> $GITHUB_OUTPUT
        else
            echo "lockfile not found, will create."
            echo "create=true" >> $GITHUB_OUTPUT
        fi
    - name: Setup Java
      uses: actions/setup-java@v4
      if: ${{ steps.check-lockfile.outputs.create }} == 'true'
      with:
        distribution: microsoft
        java-version: 17
    - name: Generate Lock File
      if: ${{ steps.check-lockfile.outputs.create }} == 'true'
      run: ./gradlew dependencies --write-locks
    - name: Upload Lockfile
      if: ${{ steps.check-lockfile.outputs.create }} == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: $LOCKFILE
        path: '**/*.lockfile'

  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    needs: [ 'lockfile' ]
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
    - uses: actions/checkout@v4
    - name: Download Lockfile
      if: ${{ needs.lockfile.outputs.lockfile }} == 'true'
      uses: actions/download-artifact@v4
      with:
        name: $LOCKFILE
    - run: semgrep ci
